/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type PageBuilder = Array<
  | ({
      _key: string;
    } & Hero)
  | ({
      _key: string;
    } & Switchback)
>;

export type Switchback = {
  _type: 'switchback';
  orientation?: 'imageLeft' | 'imageRight';
  kicker?: string;
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  cta?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'cta';
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  imageAlt?: string;
};

export type Hero = {
  _type: 'hero';
  kicker?: string;
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  cta?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'cta';
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  imageAlt?: string;
};

export type HexAsset = {
  _id: string;
  _type: 'hexAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: 'hex' | 'outline' | 'icon' | 'logo';
  name?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SeasonalData = {
  _id: string;
  _type: 'seasonalData';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  season?: number;
  title?: string;
  dreamRealm?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'unit';
  }>;
  primalLord?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'unit';
  }>;
  ravagedRealm?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'unit';
  }>;
};

export type Artifact = {
  _id: string;
  _type: 'artifact';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: 'seasonal' | 'preSeason' | 'honorDuel';
  season?: number;
  name?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type Unit = {
  _id: string;
  _type: 'unit';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: 'hero' | 'boss' | 'phantimal' | 'wildcard' | 'misc';
  name?: string;
  season?: number;
  faction?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'faction';
  };
  class?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'class';
  };
  hex?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  portrait?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type Faction = {
  _id: string;
  _type: 'faction';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  faction?:
    | 'lightbearer'
    | 'wilder'
    | 'mauler'
    | 'graveborn'
    | 'celestial'
    | 'hypogean'
    | 'dimensional'
    | 'celestial-hypogean';
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type Class = {
  _id: string;
  _type: 'class';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  class?: 'tank' | 'support' | 'marksman' | 'mage' | 'rogue' | 'warrior';
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type Page = {
  _id: string;
  _type: 'page';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  noIndex?: boolean;
  isFile?: boolean;
  content?: PageBuilder;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Cta = {
  _id: string;
  _type: 'cta';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  link?: string;
  icon?: string;
  hierarchy?: 'primary' | 'secondary' | 'tertiary';
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  imageAlt?: string;
};

export type SocialMedia = {
  _id: string;
  _type: 'socialMedia';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  type?: string;
  link?: string;
  label?: string;
  hide?: boolean;
};

export type Navigation = {
  _id: string;
  _type: 'navigation';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  label?: string;
  link?: string;
  sublinks?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'navigation';
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  imageAlt?: string;
};

export type Header = {
  _id: string;
  _type: 'header';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  navigation?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'navigation';
  }>;
};

export type Brand = {
  _id: string;
  _type: 'brand';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brand?: string;
  fullLogo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  icon?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PageBuilder
  | Switchback
  | Hero
  | HexAsset
  | SanityImageCrop
  | SanityImageHotspot
  | SeasonalData
  | Artifact
  | Unit
  | Faction
  | Class
  | Page
  | Slug
  | Cta
  | SocialMedia
  | Navigation
  | Header
  | Brand
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/utils/queries.ts
// Variable: SLUG_QUERY
// Query: *[_type == "page" && slug.current != "home"]{  slug}
export type SLUG_QUERYResult = Array<{
  slug: Slug | null;
}>;
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug]{  _id,  title,  slug,  description,  content,  isFile,}
export type PAGE_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  content: PageBuilder | null;
  isFile: boolean | null;
}>;
// Variable: LOGO_QUERY
// Query: *[_type == "brand" && brand == "Cam"]{  _id,  brand,  fullLogo,  icon}
export type LOGO_QUERYResult = Array<{
  _id: string;
  brand: string | null;
  fullLogo: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  icon: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
}>;
// Variable: SOCIAL_QUERY
// Query: *[_type == "socialMedia"]{  _id,  type,  link,  label,  hide,}
export type SOCIAL_QUERYResult = Array<{
  _id: string;
  type: string | null;
  link: string | null;
  label: string | null;
  hide: boolean | null;
}>;
// Variable: CTA_QUERY
// Query: *[_type == "cta"]{  _id,  label,  link,  hierarchy,  image,  icon,}
export type CTA_QUERYResult = Array<{
  _id: string;
  label: string | null;
  link: string | null;
  hierarchy: 'primary' | 'secondary' | 'tertiary' | null;
  image: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  } | null;
  icon: string | null;
}>;
// Variable: TAGS_QUERY
// Query: *[_type == "skill"]{  _id,  skill,  image,}
export type TAGS_QUERYResult = Array<never>;
// Variable: HEADER_QUERY
// Query: *[_type == "header"]{  navigation[]{    _key,     ...@->{      _id,      label,      link,      image,      sublinks[]{        _key,        ...@->{          _id,          label,          link,          image,        }      }    }  }}
export type HEADER_QUERYResult = Array<{
  navigation: Array<{
    _key: string;
    _id: string;
    label: string | null;
    link: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: 'image';
    } | null;
    sublinks: Array<{
      _key: string;
      _id: string;
      label: string | null;
      link: string | null;
      image: {
        asset?: {
          _ref: string;
          _type: 'reference';
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
      } | null;
    }> | null;
  }> | null;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "page" && slug.current != "home"]{\n  slug\n}': SLUG_QUERYResult;
    '*[_type == "page" && slug.current == $slug]{\n  _id,\n  title,\n  slug,\n  description,\n  content,\n  isFile,\n}': PAGE_QUERYResult;
    '*[_type == "brand" && brand == "Cam"]{\n  _id,\n  brand,\n  fullLogo,\n  icon\n}': LOGO_QUERYResult;
    '*[_type == "socialMedia"]{\n  _id,\n  type,\n  link,\n  label,\n  hide,\n}': SOCIAL_QUERYResult;
    '*[_type == "cta"]{\n  _id,\n  label,\n  link,\n  hierarchy,\n  image,\n  icon,\n}': CTA_QUERYResult;
    '*[_type == "skill"]{\n  _id,\n  skill,\n  image,\n}': TAGS_QUERYResult;
    '*[_type == "header"]{\n  navigation[]{\n    _key, \n    ...@->{\n      _id,\n      label,\n      link,\n      image,\n      sublinks[]{\n        _key,\n        ...@->{\n          _id,\n          label,\n          link,\n          image,\n        }\n      }\n    }\n  }\n}': HEADER_QUERYResult;
  }
}
